# Generated by Django 3.2.7 on 2021-10-12 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(default=None, max_length=200, null=None)),
                ('name', models.CharField(default=None, max_length=200, null=None)),
                ('first_name', models.CharField(default=None, max_length=200, null=None)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('first_day', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_dead', models.BooleanField(default=False)),
                ('virus_name_test', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
