# Generated by Django 3.2.8 on 2021-10-14 17:38

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default=None, null=None, upload_to=demo.models.user_directory_path),
        ),
    ]
