# Generated by Django 3.2.8 on 2021-10-14 18:35

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(null=None, upload_to=demo.models.user_directory_path),
        ),
    ]
